### ISSUE TITLE
Could not create deployment

### ISSUE THREAD

**Issue by baptistebriel** [zeit/now-app#109]
Error: Request failed with status code 413

Was trying to upload a simple website with an index.html file, a couple of images and CSS/JS assets -- 2MB in total.

**Comment by leo** [comment]
We're working on making [now-client](https://github.com/zeit/now-client) support streaming. When this feature lands, we'll be able to stream files to the API (like the CLI does it), instead of pushing them at once. This results in much faster upload times and you'll never see such an error again.

😊
