### ISSUE TITLE
When using nvm, now isn't set to executable

### ISSUE THREAD

**Issue by ericf** [zeit/now-app#83]
When using now.app to install the `now` CLI binary, it was installed but didn't make it executable. I had to run:
```bash
$ chmod +x /usr/local/bin/now
```

Looking at [`setPermissions()`](https://github.com/zeit/now-app/blob/b3acfe18fd0f5b0d69b7d7d04d5973ee7637ccfa/src/electron/utils/binary.js#L138-L140), it depends on the `node` binary existing in `/usr/local/bin` as well. But I use `nvm` and therefore my `node` binary exists here:
```bash
$ which node
/Users/ericferr/.nvm/versions/node/v6.6.0/bin/node
```

**Comment by leo** [comment]
That's not completely true. It automatically detects the path of node using `which` (as you can see [here](https://github.com/zeit/now-app/blob/b3acfe18fd0f5b0d69b7d7d04d5973ee7637ccfa/src/electron/utils/binary.js#L125)). In turn, always the right path is used.

The problem is probably that the app didn't have enough rights to set the permissions on the newly created binary (outside of sudo mode). Thinking about a solution!
